### ISSUE TITLE
The symbol value from "Preferred Title; symbol" should have a synonym type of abbreviation

### ISSUE THREAD

**Issue by twhetzel** [monarch-initiative/omim#119]
The symbol from the "Preferred Title; symbol" field is added as a synonym, but does not have a synonym type, which should be abbreviation.

See https://omim.org/entry/618983?search=les&highlight=les

![Screenshot 2024-07-24 at 1 28 06 PM](https://github.com/user-attachments/assets/3d1a17c6-d318-4a4a-b423-2d10fd60991f)

**Comment by joeflack4** [comment]
Need to double check, but:

> Alternative titles; symbols
> LEWIS BLOOD GROUP SYSTEM; LES

Usually just 1 label, ;, and then symbol.

But what if there are more than 1? Are they `,` delimited?
