### ISSUE TITLE
Bug: `run.sh` not working: `ModuleNotFoundError`

### ISSUE THREAD

**Issue by joeflack4** [monarch-initiative/omim#127]
## Overview
`run.sh` is currently not working, due to at least 1 package not being present in the ODK container:

`ModuleNotFoundError: No module named 'dotenv'`

## Possible solutions
For local use, could have a variation of `make all`, at least, which could have a `pip install` goal for this.

## Additional info
The GitHub action does not fail, but this doesn't work locally. I assume this is because the fixed version of ODK that the GH action is running off of does not have this same problem.

**Comment by twhetzel** [comment]
@joeflack4 is this also reported in the repo for ODK?

**Comment by joeflack4** [comment]
I don't think it's an ODK issue. Solving it might be as simple as doing a pip install of the missing package when running make all.

**Comment by gouttegd** [comment]
> The GitHub action does not fail, but this doesn't work locally. I assume this is because the fixed version of ODK that the GH action is running off of does not have this same problem.

No, the GitHub Action does not fail because [it includes a step](https://github.com/monarch-initiative/omim/blob/e81293934307a1caa7da8a5880a4e04676efbe91/.github/workflows/buid_and_release.yml#L19) to explicitly install any missing Python packages:

```yaml
- name: Install
  run: |
    make install
```

But both the [GitHub Action](https://github.com/monarch-initiative/omim/blob/e81293934307a1caa7da8a5880a4e04676efbe91/.github/workflows/buid_and_release.yml#L14) and the [local `run.sh` script](https://github.com/monarch-initiative/omim/blob/e81293934307a1caa7da8a5880a4e04676efbe91/run.sh#L39) are configured to use ODK 1.4.3, which does not include the `python-dotenv` package (it had been added in ODK 1.5).

Unless there is a compelling reason to avoid using ODK 1.5.x, the simple fix here is to use the latest version of the ODK.

**Comment by twhetzel** [comment]
Perfect, thanks for your review and comment here! This issue can be fixed as mentioned above and will take care of https://github.com/monarch-initiative/omim/issues/114 as well.

**Comment by joeflack4** [comment]
Wow, @gouttegd, didn't expect to have your help here!

I'm gonna close this issue, as the `make install` will actually solve it immediately. I don't need to update any docs either. The [readme](https://github.com/monarch-initiative/omim) already instructs to install it.

**Comment by twhetzel** [comment]
@joeflack4 how does `make install` solve this? Using the local `run.sh` still uses ODK 1.4.3 which does not have `python-dotenv`.

**Comment by joeflack4** [comment]
@twhetzel Well, technically, the [repo docs](https://github.com/monarch-initiative/omim) are right with respect to Python development, but wrong currently with respect to running the pipeline.

It says to do this:
1. `make install`
2. `sh run.sh make all`

However, that will only do the installation of Python requirements locally.

I ran this and expected it to fail as well, and it did fail:
1. `sh run.sh make install`
2. `sh run.sh make all`

It fails because the install needs to be done each time.

So I ran this, expecting it to work, and it did work:
`sh run.sh make install all`

**What to do now**
- a. Close this issue, remember to do `sh run.sh make install all` locally.
- b. Handle https://github.com/mapping-commons/sssom-py/issues/554, which should solve #114. Upgrade ODK, make sure it works, and then can close this issue.
- c. Update the docs now to say to do `sh run.sh make install all` locally and close this issue. Then, when #114 is done and ODK upgraded and working, change docs back to just `sh run.sh make all`.

**Comment by joeflack4** [comment]
Looks like we can do option 'b' now

**Comment by twhetzel** [comment]
Thank you Joe, I better understand your comment now. I see the fix in `sssom-py` is [released now](https://github.com/mapping-commons/sssom-py/issues/554#issuecomment-2437897056) - thanks @matentzn and @gouttegd  🎉 

Do we also need to wait to have this in a new version of ODK?

**Comment by matentzn** [comment]
You can either wait or at a `pip install -U sssom` inside your makegoal - which I would avoid tbh. I am sure the new version will come reasonably soon!

**Comment by twhetzel** [comment]
Yes, I'd prefer to handle this with updating to a new release of ODK.
