### ISSUE TITLE
Redundant?: `exactSynonym` copies of labels

### ISSUE THREAD

**Issue by joeflack4** [monarch-initiative/omim#131]
## Overview
At some point, we started adding an `oio:exactSynonym` for the exact string of every `rdfs:label`, e.g.:

```ttl
OMIM:100050 a owl:Class ;
    rdfs:label "aarskog syndrome, autosomal dominant" ;
    MONDO:exclusionReason MONDO:excludeTrait ;
    oboInOwl:hasExactSynonym "aarskog syndrome, autosomal dominant" .
```

However, this may now be redundant, since we started doing this for all sources in `mondo-ingest` in recent months.

Given this redundancy, should we stop doing this in OMIM?

**Comment by twhetzel** [comment]
Good catch! Sounds like adding the term label as an exact synonym could possibly be removed from the OMIM repo. However the current OMIM code and current Mondo Ingest code are not causing duplicate exact synonyms to be added to an OMIM class in the omim.owl component file in Mondo Ingest repo so it's fine to leave the omim repo code as-is for this item.
