### ISSUE TITLE
Add OMIM entries with 'somatic' in the phenotype label to "review.tsv"

### ISSUE THREAD

**Issue by twhetzel** [monarch-initiative/omim#175]
In addition to the two existing cases (digenic and self-referential) that are flagged in the "review.tsv" file, another case of "somatic" is needed. These should be any entry that contain the word "somatic" in the phenotype label from OMIM. An example of one of these is [OMIM:603956 cervical cancer](https://omim.org/entry/603956) where this did not also appear to be self-referential like the other "somatic" self-referential entries. 

The "review.tsv" file should be a file in the omim repo and should not be a Google Sheet. The file should be re-created each time the OMIM ingest is run and entries in the file should only be those found for that given run of the ingest pipeline. It's ok if an OMIM entry is repeated for different cases in the "review.tsv" if that happens.

**Comment by joeflack4** [comment]
I just checked to see if this was effectively addressed by (TLDR: it's not):
- #166 

Although it does not specifically check for 'somatic' in the label. It checks for the "self referential pattern", of which all such phenotypes do end up having "somatic" in the label ([google sheet](https://docs.google.com/spreadsheets/d/1hKSp2dyKye6y_20NK2HwLsaKNzWfGCMJMP52lKrkHtU/edit?gid=1826025296#gid=1826025296)).

But indeed, there do appear other cases in `morbidMap.txt` where 'somatic' is in the label and not occurring with this pattern.
