### ISSUE TITLE
Improve abbreviation re-casing

### ISSUE THREAD

**Issue by joeflack4** [monarch-initiative/omim#179]
## Overview
For labels, Mondo lowercases almost everything, with acronyms  being an exception. In OMIM, we apply this lowercasing and then try to figure out where the acronyms are in the label, and recapitalize them. However, this algorithm is not perfect.

Example; [Trish wrote](https://github.com/monarch-initiative/omim/pull/153#pullrequestreview-2493998547):
> Just to document, there are some capitalizations that are not completely fixed for gene entry pages, e.g. `NFKB` in https://omim.org/entry/164014?search=NFKB&highlight=NFKB.
> ```
> > AnnotationAssertion(<http://www.geneontology.org/formats/oboInOwl#hasExactSynonym> <https://omim.org/entry/164014> "RELA protooncogene, nfkb subunit")
> 87677,87678c87677
> < AnnotationAssertion(<http://www.geneontology.org/formats/oboInOwl#hasExactSynonym> <https://omim.org/entry/164014> "rela protooncogene, nfkb subunit")
> ```
> 
> However, since this case is for a gene name it's not important to fix and the data for the gene entry page doesn't support being able to fix this, e.g. NFKB, capitalization using the method in this PR so no need for further updates.

**Comment by twhetzel** [comment]
@joeflack4 no need for a ticket for this. I said that "it's not important to fix".

**Comment by joeflack4** [comment]
@twhetzel OK. I mentioned in the PR that I might create an issue for it; I marked it low priority but if you think it is no priority that is fine!
