### ISSUE TITLE
Not enough terms labeled w/ `biolink:category biolink:Disease`?

### ISSUE THREAD

**Issue by joeflack4** [monarch-initiative/omim#34]
Currently the output omim.ttl file only has 198 instances of `biolink:category biolink:Disease`-labeled terms. It should be much more than that, I have heard.

**Comment by joeflack4** [comment]
@matentzn FYI

**Comment by matentzn** [comment]
You must have been looking at the wrong file. I checked the release and it looks good with around 8200 occurrences. I think this issue can be closed.

**Comment by joeflack4** [comment]
I just ran to create a new release and got over 8200 as well. I guess I looked in the old `data/omim.ttl` file. Surprised I would make that mistake, but must be the case. Thanks for checking, Nico.
