### ISSUE TITLE
hasSynonymType needs to be declared an OWL annotation property

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/omim#35]
http://www.geneontology.org/formats/oboInOwl#hasSynonymType

always check that omim.owl can be run with ROBOT, like

```
robot convert -i omim.owl -f owl -o test.owl
```

**Comment by joeflack4** [comment]
When initializing RDF graph, drop a single triple. "subset property -> rdf:type -> owlAnnotation property"

**Comment by joeflack4** [comment]
When running `robot convert -i omim.ttl -f owl -o test.owl`, it listed a bunch of stuff that's wrong:

If I add the triple, a lot of these will disappear. But adding the above triple.

Locally, I created `omim2.ttl` and added the triple manually, and I got no errors when running the robot command! Now I just need to add this programmatically during the build process.

**Comment by joeflack4** [comment]
Added. The generated triple shows as: `oboInOwl:hasSynonymType a owl:AnnotationProperty .`

**Comment by matentzn** [comment]
Awesome, thank you!
