### ISSUE TITLE
OMIMPS URL should be https://www.omim.org/phenotypicSeries/PS

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/omim#37]
Right now, its https://www.omim.org/phenotypicSeries/ which causes entities not to resolve correctly

**Comment by matentzn** [comment]
Example of a correct one: https://www.omim.org/phenotypicSeries/PS309530

**Comment by joeflack4** [comment]
@matentzn I think you must have been looking at an older version. I checked, and the last release, published on October 1st, already uses the correct URL for the OMIMPS prefix:

From `omim.ttl` in [latest release](https://github.com/monarch-initiative/omim/releases/tag/1.0.0), line 6:
```
@prefix OMIMPS: <http://www.omim.org/phenotypicSeries/PS> .
```

As such, I'm gonna mark this closed. But if I misunderstood something, please re-open!

**Comment by matentzn** [comment]
https, not http :)

**Comment by matentzn** [comment]
- [ ] When done, remind  me in slack to update Mondo old slurping code

**Comment by joeflack4** [comment]
Done and done~
