### ISSUE TITLE
URI with http or https

### ISSUE THREAD

**Issue by hrshdhgd** [monarch-initiative/omim#42]
The "id" is `OMIM.json` has `http:` for e.g. `"id" : "http://omim.org/entry/276000",` . Is this correct or should this be ` "id" : "https://omim.org/entry/276000",`

cc: @matentzn

**Comment by matentzn** [comment]
@joeflack4 this should be fixed already, can you confirm?

**Comment by joeflack4** [comment]
Yep! I should've closed this.
