### ISSUE TITLE
Create a complete UMLS-OMIM SSSOM mapping file

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/omim#46]
Covering all diseases in OMIM.

See #44, should be attached to release.

**Comment by joeflack4** [comment]
This sounds like it should be easy to do with what I have available.

For my input, I'd use the latest `omim.ttl` from our OMIM ingest.

That file already has mappings to UMLS in the form of:
`oboInOwl:hasDbXref UMLS:<code>`

For the UMLS prefix, the one we've been using and which I'll continue to use will be:
`http://linkedlifedata.com/resource/umls/id/`

If any of this sounds incorrect, just let me know.

**Comment by matentzn** [comment]
- instead of hasDbXref, for the sssom file, use `skos:exactMatch`.
- For Mondo related work, lets consolidate our prefixes here: https://github.com/monarch-initiative/mondo/blob/master/src/ontology/metadata/mondo.sssom.config.yml

**Comment by joeflack4** [comment]
Got it!

**Comment by joeflack4** [comment]
Results in latest release. I think I still need to split the file, though: https://github.com/monarch-initiative/omim/releases/tag/latest
