### ISSUE TITLE
OMIM terms with `None` label

### ISSUE THREAD

**Issue by joeflack4** [monarch-initiative/omim#67]
## Overview
I was looking at some `mondo-ingest` outputs for OMIM, and noticed `'None'` as the label for some terms. I looked at `omim.owl` and saw that they are showing as `'None'` there as well.

I would imagine that this is a bug in the OMIM ingest.

Here's an example of something with a legit label that ended up with a `'None'` label.

Our `omim.owl`:
```owl
    <owl:Class rdf:about="https://omim.org/entry/143040">
        <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/SO_0000704"/>
        ...
        <rdfs:label>None</rdfs:label>
        <skos:exactMatch rdf:resource="http://linkedlifedata.com/resource/umls/id/C1840473"/>
        <vocab:category rdf:resource="https://w3id.org/biolink/vocab/Gene"/>
    </owl:Class>
```

Online entry for https://omim.org/entry/143040:
> ANTIGEN DEFINED BY MONOCLONAL ANTIBODY F10.44.2

## Related
https://github.com/monarch-initiative/mondo-ingest/issues/84

**Comment by matentzn** [comment]
Oh ok, yes, solving this is is important. Thanks for catching. Hopefully this is an easy fix. Better not to have a label at all then to have a label "None"
