### ISSUE TITLE
Bug: Matching on abbreviations

### ISSUE THREAD

**Issue by joeflack4** [monarch-initiative/omim#70]
## Overview
Nicole V mentioned today that this is the only thing she knows thats wrong w/ the OMIM ingest currently. We have matchings that are sometimes done on abbreviations.

I'm not sure where in the ingest it is doing this at the moment.

Example of the problem (row within the following [Google Sheet: unmapped_omim_lex](https://docs.google.com/spreadsheets/d/1KPGxCeQue7mNmSSQoLrMMnfelQrUVAKQj4tbLsLSoT0/edit#gid=398515198)):
```tsv
subject_id	subject_label	predicate_id	object_id	mapping_justification	object_label	comment	mapping_tool	confidence	subject_match_field	object_match_field	match_string	Y/N	Comment
MONDO:0019105	renal nutcracker syndrome	MONDO:equivalentTo	OMIM:259775	semapv:LexicalMatching	raine syndrome	LEXMATCH	oaklib	0.8	oio:hasExactSynonym	oio:hasExactSynonym	rns	N	matching on abbreviation
```

**Comment by nicolevasilevsky** [comment]
I think we should just keep doing the mapping this way (matching on abbreviations) and have me and @sabrinatoro review them. Because if we don't match on them, we may lose some potential mappings.

**Comment by joeflack4** [comment]
@nicolevasilevsky Alright, that sounds fine to me!
