### ISSUE TITLE
`morbidmap.txt`: `RO:0003302` when multiple rows / gene::disease relationships

### ISSUE THREAD

**Issue by joeflack4** [monarch-initiative/omim#75]
## Overview
At the Mondo technical meeting today, Nico asked me to investigate whether or not there were phenotypes/disorders that had multiple rows in `morbidmap.txt`. I did an investigation and found that there are.

**Example**
In this example, the `Phenotype` in question has the label `{Type 2 diabetes mellitus, susceptibility to}`. Full label is `{Type 2 diabetes mellitus, susceptibility to}, 125853 (3)`. I actually don't know what the significance of the curly braces are. It can be seen though that even though the `Phenotype` appears multiple times, these are not duplicate rows. 
```tsv
Phenotype	Gene Symbols	MIM Number	Cyto Location
{Type 2 diabetes mellitus, susceptibility to}, 125853 (3)	GPD2	138430	2q24.1
{Type 2 diabetes mellitus, susceptibility to}, 125853 (3)	HMGA1, HMGIY	600701	6p21.31
{Type 2 diabetes mellitus, susceptibility to}, 125853 (3)	IRS1	147545	2q36.3
{Type 2 diabetes mellitus, susceptibility to}, 125853 (3)	NEUROD1, T2D	601724	2q31.3
```

### 1. Mult rows ok?
This makes sense to me. @matentzn I don't think this is a concern that there are multiple rows, right? 

### 2. Did I add this info to the RDF correctly?
I added the `biolink:has_evidence` to the entry for the MIM# in the `MIM Number` column (e.g. `138430`), not the MIM# within the `Phenotype` label (e.g. `125853`)

MIM# in the `MIM Number` column (e.g. `138430`)
```ttl
OMIM:138430 a owl:Class ;
    rdfs:label "GPD2" ;
    IAO:0000142 PMID:10954707,
        ...
        PMID:9070847 ;
    RO:0002525 CHR:9606chr2q24.1 ;
    RO:0003303 OMIM:125853 ;
    oboInOwl:hasExactSynonym "GPD2",
        "gdh2",
        "glycerol-3-phosphate dehydrogenase 2",
        "glycerophosphate dehydrogenase-2 ca(2+)-responsive mitochondrial fad-linked",
        "gpd, mitochondrial" ;
    rdfs:subClassOf SO:0000704 ;
    skos:exactMatch UMLS:C1415200,
        HGNC:4456,
        HGNC_symbol:GPD2,
        NCBIGene:2820 ;
    biolink:category biolink:Gene ;
    biolink:has_evidence "The molecular basis for the disorder is known; a mutation has been found in the gene." .
```

MIM# within the `Phenotype` label (e.g. `125853`)
```ttl
OMIM:125853 a owl:Class ;
    rdfs:label " iia 2 diabetes mellitus" ;
    IAO:0000142 PMID:10199785,
        ...
        PMID:9892237 ;
    oboInOwl:hasExactSynonym " iia 2 diabetes mellitus",
        "T2D",
        "diabetes mellitus,  iia 2",
        "diabetes mellitus,  iia 2, protection against",
        "diabetes mellitus, noninsulin-dependent",
        "insulin resistance, susceptibility to",
        "maturity-onset diabetes",
        "noninsulin-dependent diabetes mellitus" ;
    skos:exactMatch UMLS:C0011860 ;
    biolink:category biolink:Disease .
```

## Additional info
Here's an attachment that shows all the phenotype labels which appear in multiple rows, and how many rows they appear in. 
[phenos_with_mult_rows.json.zip](https://github.com/monarch-initiative/omim/files/9892368/phenos_with_mult_rows.json.zip)

## Related
- #77

**Comment by joeflack4** [comment]
@sabrinatoro @matentzn Take a look at the results and my questions here. Also here is a link to the new release where you can download the latest `omim.ttl`: https://github.com/monarch-initiative/omim/releases/tag/2022-10-27

**Comment by sabrinatoro** [comment]
The curly brakets means this is a susceptibility term. 
The phenotypes in the morbitmap that have more than one gene per disease should not be brought into Mondo. 
If I understand correctly, the omim.ttl file is what we bring into Mondo: the gene is brought up as "causes condition" (RO:0003303) - omim phenotype. If I understand correctly, I can find at least 1 example of 1 disease (OMIM:254090) that is associated with more than one gene (OMIM:120250 "COL6A3", OMIM:120240 "COL6A2", OMIM:120220 "COL6A1"). This is not correct because of the reason above.

**Comment by matentzn** [comment]
@sabrinatoro can you raise this in meeting?

**Comment by nicolevasilevsky** [comment]
we should use relationship 'contributes to'

**Comment by joeflack4** [comment]
@matentzn @sabrinatoro I want your thoughts/judgement: Sabrina has [determined some new predicates](https://github.com/monarch-initiative/omim/issues/79#issuecomment-1319408780) for each type of mapping evidence. For cases where there are 2+ types of mapping evidence, we want to use `RO:0003302` as Nicole stated above. My question is, do we want to:

(a) Only add relationship using`RO:0003302`, or
(b) Add `RO:0003302`, but also keep the other relationships, too.

I'm pretty sure we decided on (a). It feels lossy to me but I'm not an expert. In any case, I'm doing (a), but if I should do (b), let me know.

**Comment by matentzn** [comment]
I think (a) is fine. But 

- [ ] document that decision in https://github.com/monarch-initiative/mondo-ingest/blob/main/src/ontology/metadata/omim.yml

**Comment by joeflack4** [comment]
Sounds good. I have collected this in my docs todo's.
I assume you maybe meant? https://github.com/monarch-initiative/mondo-ingest/blob/main/docs/sources/omim.md

**Comment by joeflack4** [comment]
@matentzn @sabrinatoro Just want to clarify just in case I misunderstood something.

## Example cases
### 1. Multiple rows, same mapping key (3)
```tsv
Phenotype	Gene Symbols	MIM Number	Cyto Location
{Type 2 diabetes mellitus, susceptibility to}, 125853 (3)	GPD2	138430	2q24.1
{Type 2 diabetes mellitus, susceptibility to}, 125853 (3)	HMGA1, HMGIY	600701	6p21.31
```

### 2. [Multiple rows, different mapping keys (3) & (4)](https://github.com/monarch-initiative/omim/issues/81)
```tsv
Phenotype	Gene Symbols	MIM Number	Cyto Location
Neurodevelopmental disorder with hypotonia, stereotypic hand movements, and impaired language, 613443 (3)	MEF2C, C5DELq14.3, DEL5q14.3, NEDHSIL	600662	5q14.3
Chromosome 5q14.3 deletion syndrome, 613443 (4)	MEF2C, C5DELq14.3, DEL5q14.3, NEDHSIL	600662	5q14.3
```

## What I believe I'm supposed to do
i. For both example cases of (1) and (2) above, I'm going to add 1 gene::disease relationship (using the new reified structure) for for each row.
ii. For both example cases of (1) and (2) above, the predicate will always be `RO:0003302` (causes or contributes to).

I am mainly wanting to double check if (ii). Particularly in example case (2), if _all_ of the rows use the same mapping predicate, e.g. `(3)`, do I really want to use `RO:0003302` when [@sabrinatoro has determined](https://github.com/monarch-initiative/omim/issues/79#issuecomment-1319408780) that `RO:0004013` (is causal germline mutation in) is the most appropriate for these cases?

For now, I will use `RO:0003302` in both of the example cases above until I hear otherwise.

**Comment by matentzn** [comment]
I will let @sabrinatoro answer this, but, in example two, is the `disease` (`phenotype`) in both rows the same, because 613443 is in the label? The first part of the label sounds so.. different to a layperson like me.

**Comment by joeflack4** [comment]
I can help elaborate on what I mean. In the _example case 2_ , the `Phenotype` field for the second row is:
> `Chromosome 5q14.3 deletion syndrome, 613443 (4)`

This `Phenotype` field consists of 3 parts:
i. Label: `Chromosome 5q14.3 deletion syndrome`
ii. MIM#: `, 613443`
iii. Mapping evidence key: ` (4)`

At least, 'label' is what I call it. I suppose you could also call it a 'title' or 'name'.

**Comment by sabrinatoro** [comment]
it looks like this is the example where the disease/phenotype that are in both rows represent 2 different diseases (though they have the same OMIM id; one is an "included" term.

Otherwise your plan makes sense (I think)

**Comment by joeflack4** [comment]
Hmmmmm... Could it be that all such instances of this label variation are such that one of the labels is the main label, and the rest of them are ", INCLUDED" labels? Not sure. @matentzn If you want, at some point I could do an analysis like this: (i) group the MIMs and their label variations from `morbidmap.txt`, (ii) fetch all label variations for given MIMs in `mimTitles.txt`, (iii) check if the above hypothesis is correct.
