### ISSUE TITLE
MIM titles with ", INCLUDED"

### ISSUE THREAD

**Issue by joeflack4** [monarch-initiative/omim#82]
## Overview
@sabrinatoro @ nicolevasilevsky I wasn't sure whether to make an issue in `mondo` or `mondo-ingest` so I just made it here.

From last meeting:
> give Sabrina and Nicole a list of ‘included’ terms, and these should be added as new terms with the annotation ‘OMIM:includedInOMIM’

I linked this list in some issue but I couldn't find it, so I just generated it again (mostly `cat mimTitles.txt | grep ", INCLUDED"`)
[mimTitlesWithWordIncluded.tsv.zip](https://github.com/monarch-initiative/omim/files/10015730/mimTitlesWithWordIncluded.tsv.zip)

There are about 1,300 such ", INCLUDED"-labeled terms, out of about ~28,000 (~5%).

## Task
- [x] Joe: give Sabrina and Nicole a list of ‘included’ terms
- [ ] Nicole/Sabrina: and these should be added as new terms with the annotation ‘OMIM:includedInOMIM

**Comment by nicolevasilevsky** [comment]
thanks @joeflack4, this is perfect. I'll take it from here. We can close this issue here
