### ISSUE TITLE
Remove `omim.ttl` from commits?

### ISSUE THREAD

**Issue by joeflack4** [monarch-initiative/omim#95]
## Overview
I think we had previously commit it for convenience, but now especially with weekly releases, I'm not sure that's helpful.

**Comment by matentzn** [comment]
I think it's fine to commit it, this gives us a proper version history of the file! The important thing is to recreate it each time!

**Comment by joeflack4** [comment]
I suppose that's true, but right now the GitHub action doesn't commit it; just makes a release.

**Comment by matentzn** [comment]
In this case: delete for sure

**Comment by joeflack4** [comment]
Completed by: https://github.com/monarch-initiative/omim/commit/da7c795b2149824c84a8d1e15234b7ab7f6c7b42
